# .github/dependabot.yml
version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Group all GitHub Action updates into one PR
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain Nix flake inputs
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    # Group all Nix updates into one PR
    groups:
      nix:
        patterns:
          - "*"
