# .mdformat.toml
wrap = 80                       # Core option
number = true                   # Core option
end_of_line = "lf"              # Core option

# Options for an extension like mdformat-gfm
[plugin.gfm]
# plugin specific option here
